### ISSUE TITLE
Tango Core source & implementation

### ISSUE THREAD

**Issue by zharvey-welltok** [tomthecarrot/arcore-for-all#32]
I'm interested in learning how ARCore works under the hood -- I tried building my own AR library about a year ago (based off of a pipeline using OpenMVG, MVE and mvs-texturing) and I failed spectacularly.

I decompiled the `classes.jar` and took a gander at it's source. If I'm not mistaken, it looks like Google ARCore is *actually* a Java wrapper (adding a few graphics & math support classes) around Google's Tango Core platform yes? And looking in the `TangoClientLibLoader` class, it *appears* that the lion's share of Tango's core functionality is written in native C (I see references to a `libtango_client_api` lib, etc.).

I'm really interested in learning what (specific) AR/computer vision/3D reconstruction/SfM techniques Tango is implementing here (mostly because I'm **jealous** that it works so great and I failed so miserably!!!), and especially how they're accomplishing AR in real-time (on the rare occasions when my pipeline *did* work, I had to take a video on my phone, pass it into my software/pipeline and it took about 30+ minutes to process!).

Just wondering if anybody here has insight into:

* How ARCore/Tango Core work (what techniques/algorithms/etc. are employed); and
* Where I might be able to find Tango Core's source (the meat + potatoes native C implementation; not the Java wrapper around it)

Thanks for any-and-all info! Keep up the great work!

**Comment by lvonasek** [comment]
From Lenovo Phab2Pro I opened Settings/Tango/Licences. There I can see that it is using this libraries:
AOSP, BoringSSL (extended with ISC), OpenSSL, Orignal SSLeay, Ceres Solver, Eigen, gflags, glog, GRPC, Intel Threading Building Blocks, ion, LAPACK, libnabo, NVIDIA CUB, octree, OpenCV, Protocol Buffers, ROS cpp_common, ROS cv_bridge, ROS gencpp, ROS rosbag_direct_write, sparsehash, SQLite, TinyXML, yaml_cpp

I recently updated my Tango app with tango_client_api.so from ARcore-preview and it works ok. So you can get headers of this library here: https://github.com/googlesamples/tango-examples-c/tree/release-m20

**Comment by zharvey-welltok** [comment]
Thanks @lvonasek - am I understanding the relationship between ARCore and Tango Core correctly? My understanding is that:

* Tango Core (aka `libtango_client_api`) is a native C lib where all the heavy lifting (3D reconstruction algorithms, SfM, etc.) is taking place
* Tango Java Library is a Java library wrapping/invoking Tango Core
* ARCore uses the Java Tango Library and is adding some helper/classes and extra features on top of what Tango provides

Is my understanding correct? If not, then what is the "division of labor" between Tango and ARCore? Thanks again!

**Comment by lvonasek** [comment]
The first point is not correct, libtango_client_api is just another interpreter.

The magic is done in libtango_service_library (note it has 20MB, other libs have less than 1MB).
It is something called AreaDescription - on photos are found points which are possible to track (it is called features). When enough of this points are visible you can calculate relative camera position.
More here: https://developers.google.com/tango/overview/area-learning

In Tango there is infra sensor to read depth and using Tango3DR library you can do 3D reconstruction.
Tango3DR library can work stadalone but Google stopped updating it.

ARcore is just branch of Tango where:
-they removed Tango3DR
-they used normal camera for area learning instead of fishcamera
-they used area description features to generate point cloud
-they made impossible to install it on Tango devices

**Comment by zharvey-welltok** [comment]
Thanks again! So it *sounds* like ARCore isn't adding any new capabilities/features beyond what Tango offers; that its just using different techniques to accomplish this "area learning", yes?

Also do you know if `libtango_service_library` and `libtango_client_api` C code is open source? I can't find it anywhere! It would be *great* if I could get my hands on it! Thanks again so much!

**Comment by lvonasek** [comment]
Yes, exactly.

Tango libraries are not open source (thats why they are so buggy :D )
Anyway there is opensource alternative called RTABMAP
