### ISSUE TITLE
Support for Android Emulator

### ISSUE THREAD

**Issue by zharvey-welltok** [tomthecarrot/arcore-for-all#35]
According to the [Google ARCore Getting Started Guide](https://developers.google.com/ar/develop/java/getting-started), under *Preparing your device*:

> "*You must use a supported, physical device. ARCore does not support virtual devices such as the Android Emulator...*"

I'm wondering if anyone in this community understands **why**? That is, why does the ARCore SDK not support the Android Emulator? Is it something that can be hacked around, maybe decompiling some code (?), refactoring it, recompiling it, etc.?

I ask because I have neither a Pixel nor an S8 but would *love* to start tinkering around with the ARCore API. Any ideas here? And apologies if this isn't the right place to turn to for this sort of info, I'm just inferring that this is a repo/project for folks who are interested in hacking at ARCore to make it more open & inclusive, etc.! :-)

Thanks!

**Comment by pawangiri** [comment]
Hi @zharvey-welltok, the primary reason for ARCore not to work on Emulator is because the it relies on multiple sensors and not just camera. It needs to read the device moment by computing parallax and combining data from accelerometer and gyroscope. Emulators cannot provide that for now, also how do you propose to position the object on the surface ?

**Comment by zharvey-welltok** [comment]
Makes sense - thanks!

**Comment by pedrosax** [comment]
Google ARCore now runs in the Android Emulator:  https://developers.google.com/ar/develop/java/emulator
