### ISSUE TITLE
Samsung Galaxy S8 ROM on Samsung Galaxy S7 Edge?

### ISSUE THREAD

**Issue by gestaltermedien** [tomthecarrot/arcore-for-all#68]
What do you think would it be possible to use ARCore with a flashed Galaxy 8 ROM on a Galaxy S7 Edge?

**Comment by balabas** [comment]
Successfully runing using modified arcore_client.aar on custom S8+ port for S7.

**Comment by cadguycad** [comment]
@balabas can you tell me which rom you used? i would love to try this on my s7

**Comment by balabas** [comment]
I used [this custom firmware](https://4pda.ru/forum/index.php?showtopic=734979&st=9460#entry59260423)

**Comment by ChristophGeske** [comment]
@balabas I flashed the Masik™ Nougat 3.3 you recommended onto my S7 (SM-G930F) and after that I installed the modified arcore-preview.apk and the sample.apk (HalloAR). Unfortunately when starting the HalloAR App I got the same errors (tango core keeps stopping and HalloAR has stopped ).  
You wrote "Successfully running using modified arcore_client.aar" but I am not exactly sure what you mean by that. Do you mean you created your own ARCore app and you added the modified arcore_client.aar file to make it run on your S7 with Galaxy 8 ROM? Would be great if you could give some advise how to get ARCore running on the Galaxy S7. 

@cadguycad Did you succeed in getting ARCore running on your S7? I did not and I would love to know how it works.

Thanks to both of you for your help.

**Comment by balabas** [comment]
I just replaced default arcore_client.aar to modified in sources of "java_arcore_hello_ar" from <ARCore SDK Folder>/samples/, then i install compilled project.

**Comment by ChristophGeske** [comment]
@balabas I understand what you did now. But how did you solve the issue with tango stopping when you start the App on your S7 or did that never happen to you? 
I tried the normal ARCore Service (arcore-preview.apk) and the modified version but both of them lead to the same result the app starts, the line "Searching for surface..." appears but then a pop up tells me that "Tango Core keeps stopping". 
Have you made any other changes to your phone beside flashing the Masik™ Nougat 3.3 ROM or are you using a different ARCore Service apk? 

Thank you for you help.

**Comment by balabas** [comment]
@ChristophGeske No, i did not made any other changes to my phone after flashing, only install arcore-preview-modified.apk.

**Comment by ChristophGeske** [comment]
@balabas Encouraged by your comment I tried it again and flashed a different ROM and I got it to run on my S7 (SM-G930F). 
I used the "S8 FULL PORT FOR S7 & S7 EDGE by ambasadii [v7.0]" ROM which can be downloaded here:
https://forum.xda-developers.com/s7-edge/development/rom-s8-port-s7-s7-edge-ambasadii-t3619548

There are some problems like losing the surfaces tracking and a heavy drift if the camera position changes, but at least no "Tango Core keeps stopping" error anymore. 
Maybe playing around with other ROMs or checking out a S8 instead of the S8+ ROM will help to reduce the drift and surface problems.  

Do you also experience heavy surface drift and loss of surface tracking or is everything working smoothly on your device?

**Comment by balabas** [comment]
@ChristophGeske Yes, I've seen theese problems. I don't think, that it depeneds on ROM. It's only detection problems. I believe that the problems are caused by calibration data, which for S7 hardware is not available.

**Comment by ChristophGeske** [comment]
For all of you who are interested in flashing a ROM in order to use the ARCore on your S7 here are some more things I learned.
I am using the so called batman ROM (https://forum.xda-developers.com/galaxy-s8/development/rom-batman-rom-v1-0-0-t3618388) now which works much better than all the other ROMs mentioned above. 
With this ROM you don't even need the modified ARCore Service (modified-arcore-preview.apk) you can use the standard ARCore Service instead.
The tracking is acceptable if you move slowly and there are lots of things on your table for the camera to set the tracking points on. 
I made some special choices when flashing the ROM in order to keep my phone and my Gear VR working correctly. 
- In the ROM installation menu don't change the device.prop to S8 and install the GearVR Service so that the GearVR keeps working after flashing the ROM. Changing the device.prop to S8 might allow you to install the ARCore apps directly from the PlayStore so choosing that option might be advantageous when not using a GearVR.
- stay with the default camera and don't install the advanced camera to avoid camera errors.

I tested a few ARCore apps and they all worked for me. I also got inside out tracking to run on my Gear VR which is awesome but after 10 minutes the phone needs to cool down. I don't know how well the tracking is on a real S8 but I guess it is a bit better so don't be disappointed if the tracking is not as good as shown in all the advertisements.

**Comment by tomthecarrot** [comment]
Thank you for your instructions @ChristophGeske!
