### ISSUE TITLE
Is 32bit ever likely to be supported/modified?

### ISSUE THREAD

**Issue by pretzelzzz** [tomthecarrot/arcore-for-all#72]
I would love to try even simple graphic arcore experiences on my 32 bit phone (oneplus one snapdragon 801). What do you think is the chance they'll ever open it up to us poorer users? We don't all need high fidelity graphics... Most current VR and AR apps run just fine still on my phone...

**Comment by tomthecarrot** [comment]
The issue here is that Google's library seems to have been built for 64-bit architectures only (see [issue #13](https://github.com/tomthecarrot/arcore-for-all/issues/13#issuecomment-328300515)), so we can't run it on 32-bit architectures. This is something that we cannot modify; we'll have to wait for Google. Sorry!
